import { StyleSheet } from "@react-pdf/renderer";
import type { ReceiptPdfTheme } from "@prisma/client";

const GOLD = "#FFD700";
const BLACK = "#000000";
const WHITE = "#FFFFFF";
const MUTED_DARK = "#9CA3AF";
const LINE_DARK = "#3F3F46";

/** Estilos do tema escuro (original). */
export const receiptPdfStylesDark = StyleSheet.create({
  page: {
    paddingTop: 18,
    paddingBottom: 22,
    paddingHorizontal: 28,
    fontFamily: "Helvetica",
    fontSize: 8,
    color: WHITE,
    backgroundColor: BLACK,
  },
  /** Faixa dourada no topo do card unificado (oficina + cliente). */
  goldBarInCard: {
    height: 3,
    width: "100%",
    backgroundColor: GOLD,
    marginBottom: 0,
  },
  combinedCard: {
    borderWidth: 1,
    borderColor: LINE_DARK,
    borderRadius: 8,
    marginBottom: 8,
    overflow: "hidden",
  },
  combinedCardInner: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 0,
  },
  logoWrap: { width: 70, marginRight: 10 },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: GOLD,
  },
  headerText: { flexGrow: 1, paddingTop: 2 },
  docKind: {
    fontSize: 7,
    letterSpacing: 1.2,
    color: MUTED_DARK,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: "row",
    marginBottom: 3,
    alignItems: "flex-start",
  },
  metaLabel: {
    width: "26%",
    fontFamily: "Helvetica-Bold",
    fontSize: 7.5,
    color: GOLD,
  },
  metaValue: {
    width: "74%",
    fontSize: 7.5,
    color: WHITE,
  },
  refLine: { marginTop: 4, fontSize: 7, color: MUTED_DARK },
  /** Cliente/veículo dentro do mesmo card escuro da oficina. */
  customerInCard: {
    marginTop: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: LINE_DARK,
  },
  sectionGoldDivider: {
    height: 2,
    width: "100%",
    backgroundColor: GOLD,
    marginTop: 0,
    marginBottom: 6,
  },
  twoCol: { flexDirection: "row" },
  col: { flexGrow: 1, width: "48%" },
  fieldBlock: { marginBottom: 4 },
  fieldLabel: {
    color: GOLD,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    textTransform: "uppercase",
    marginBottom: 1,
    letterSpacing: 0.3,
  },
  fieldValue: {
    color: WHITE,
    fontSize: 8,
    lineHeight: 1.2,
  },
  tableTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    color: GOLD,
    marginBottom: 4,
    letterSpacing: 0.4,
  },
  blockSection: { marginTop: 3, marginBottom: 2 },
  blockTableTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    color: GOLD,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  /** Blocos de linhas: título + tabela. */
  lineItemsGroup: { width: "100%", marginBottom: 5 },
  lineItemsGroupSpaced: { marginTop: 8 },
  clientSectionTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 8.5,
    color: GOLD,
    marginBottom: 3,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: GOLD,
    color: BLACK,
    fontFamily: "Helvetica-Bold",
    paddingVertical: 3,
    paddingHorizontal: 5,
    fontSize: 6.5,
  },
  tableHeaderText: { color: BLACK },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: LINE_DARK,
    paddingVertical: 3,
    paddingHorizontal: 5,
  },
  tableRowAlt: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: LINE_DARK,
    paddingVertical: 3,
    paddingHorizontal: 5,
    backgroundColor: "#0C0C0C",
  },
  tableCell: { color: WHITE, fontSize: 7.5 },
  colKind: { width: "11%", textAlign: "center" },
  colPart: { width: "33%" },
  colQty: { width: "9%", textAlign: "center" },
  colUnit: { width: "22%", textAlign: "right" },
  colTot: { width: "25%", textAlign: "right" },
  colPartsDesc: { width: "44%" },
  colPartsQty: { width: "10%", textAlign: "center" },
  colPartsUnit: { width: "22%", textAlign: "right" },
  colPartsTot: { width: "24%", textAlign: "right" },
  colServDesc: { width: "68%" },
  colServVal: { width: "32%", textAlign: "right" },
  noteBox: {
    marginTop: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: LINE_DARK,
    borderRadius: 3,
  },
  noteLabel: {
    fontFamily: "Helvetica-Bold",
    fontSize: 6.5,
    color: GOLD,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  noteText: { fontSize: 7, color: MUTED_DARK, lineHeight: 1.3 },
  paymentLine: { fontSize: 7, color: MUTED_DARK, textAlign: "right" },
  /** Totais finais: risco + linhas, sem “caixa” (recibo de cliente). */
  clientTotalsBlock: {
    width: "100%",
    marginTop: 4,
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: LINE_DARK,
  },
  totalBreakdownRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  totalBreakdownLabel: {
    fontSize: 7.5,
    color: "#D4D4D8",
    fontFamily: "Helvetica",
    flexGrow: 1,
    paddingRight: 8,
  },
  totalBreakdownValue: { fontSize: 7.5, color: WHITE, textAlign: "right" },
  totalToPayRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  totalToPayRowGapped: {
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: LINE_DARK,
  },
  totalDocumentGeralRow: { width: "100%", marginBottom: 2 },
  totalDocumentGeralText: {
    fontSize: 6,
    color: MUTED_DARK,
  },
  totalToPayLabel: {
    color: GOLD,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    paddingRight: 6,
  },
  totalToPayValue: { color: GOLD, fontFamily: "Helvetica-Bold", fontSize: 11.5 },
  totalPaymentBlock: { width: "100%", marginTop: 2, alignItems: "flex-end" },
  grandBlock: { marginTop: 4, width: "100%" },
  footer: {
    marginTop: 10,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: LINE_DARK,
  },
  footerText: {
    fontSize: 6.5,
    color: MUTED_DARK,
    textAlign: "center",
    lineHeight: 1.25,
  },
});

const STONE_50 = "#FAFAF9";
const STONE_200 = "#E7E5E4";
const STONE_500 = "#78716C";
const STONE_800 = "#292524";
const STONE_900 = "#1C1917";
const AMBER_800 = "#92400E";
const HEADER_BG = "#18181B";

/** Tema claro: cabeçalho escuro, corpo tipo recibo em papel. */
export const receiptPdfStylesLight = StyleSheet.create({
  page: {
    paddingTop: 18,
    paddingBottom: 22,
    paddingHorizontal: 28,
    fontFamily: "Helvetica",
    fontSize: 8,
    color: STONE_900,
    backgroundColor: "#F5F5F4",
  },
  headerCard: {
    backgroundColor: HEADER_BG,
    borderRadius: 8,
    marginBottom: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#27272A",
  },
  goldBarInCard: {
    height: 3,
    width: "100%",
    backgroundColor: GOLD,
    marginBottom: 0,
  },
  headerInner: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 12,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 0,
  },
  logoWrap: { width: 70, marginRight: 10 },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2,
    borderColor: GOLD,
  },
  headerText: { flexGrow: 1, paddingTop: 2 },
  docKind: {
    fontSize: 7,
    letterSpacing: 1.2,
    color: "#A1A1AA",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: "row",
    marginBottom: 3,
    alignItems: "flex-start",
  },
  metaLabel: {
    width: "26%",
    fontFamily: "Helvetica-Bold",
    fontSize: 7.5,
    color: GOLD,
  },
  metaValue: {
    width: "74%",
    fontSize: 7.5,
    color: WHITE,
  },
  refLine: { marginTop: 4, fontSize: 7, color: "#A1A1AA" },
  customerInCard: {
    marginTop: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#3F3F46",
  },
  sectionGoldDivider: {
    height: 2,
    width: "100%",
    backgroundColor: GOLD,
    marginTop: 0,
    marginBottom: 6,
  },
  twoCol: { flexDirection: "row" },
  col: { flexGrow: 1, width: "48%" },
  fieldBlock: { marginBottom: 4 },
  fieldLabel: {
    color: GOLD,
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    textTransform: "uppercase",
    marginBottom: 1,
    letterSpacing: 0.3,
  },
  fieldValue: {
    color: WHITE,
    fontSize: 8,
    lineHeight: 1.2,
  },
  tableTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 8,
    color: STONE_800,
    marginBottom: 4,
    letterSpacing: 0.4,
  },
  blockSection: { marginTop: 3, marginBottom: 2 },
  blockTableTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    color: STONE_800,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  lineItemsGroup: { width: "100%", marginBottom: 5 },
  lineItemsGroupSpaced: { marginTop: 8 },
  clientSectionTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    color: STONE_800,
    marginBottom: 3,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: GOLD,
    color: BLACK,
    fontFamily: "Helvetica-Bold",
    paddingVertical: 3,
    paddingHorizontal: 5,
    fontSize: 6.5,
  },
  tableHeaderText: { color: BLACK },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: STONE_200,
    paddingVertical: 3,
    paddingHorizontal: 5,
    backgroundColor: WHITE,
  },
  tableRowAlt: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: STONE_200,
    paddingVertical: 3,
    paddingHorizontal: 5,
    backgroundColor: STONE_50,
  },
  tableCell: { color: STONE_900, fontSize: 7.5 },
  colKind: { width: "11%", textAlign: "center" },
  colPart: { width: "33%" },
  colQty: { width: "9%", textAlign: "center" },
  colUnit: { width: "22%", textAlign: "right" },
  colTot: { width: "25%", textAlign: "right" },
  colPartsDesc: { width: "44%" },
  colPartsQty: { width: "10%", textAlign: "center" },
  colPartsUnit: { width: "22%", textAlign: "right" },
  colPartsTot: { width: "24%", textAlign: "right" },
  colServDesc: { width: "68%" },
  colServVal: { width: "32%", textAlign: "right" },
  noteBox: {
    marginTop: 5,
    padding: 5,
    borderWidth: 1,
    borderColor: STONE_200,
    borderRadius: 3,
    backgroundColor: WHITE,
  },
  noteLabel: {
    fontFamily: "Helvetica-Bold",
    fontSize: 6.5,
    color: AMBER_800,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  noteText: { fontSize: 7, color: STONE_800, lineHeight: 1.3 },
  paymentLine: { fontSize: 7, color: STONE_500, textAlign: "right" },
  clientTotalsBlock: {
    width: "100%",
    marginTop: 4,
    paddingTop: 5,
    borderTopWidth: 1,
    borderTopColor: STONE_200,
  },
  totalBreakdownRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    marginBottom: 3,
  },
  totalBreakdownLabel: {
    fontSize: 7.5,
    color: STONE_800,
    fontFamily: "Helvetica",
    flexGrow: 1,
    paddingRight: 8,
  },
  totalBreakdownValue: { fontSize: 7.5, color: STONE_800, textAlign: "right" },
  totalToPayRow: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  totalToPayRowGapped: {
    marginTop: 4,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: STONE_200,
  },
  totalDocumentGeralRow: { width: "100%", marginBottom: 2 },
  totalDocumentGeralText: { fontSize: 6, color: STONE_500 },
  totalToPayLabel: {
    color: STONE_900,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
    paddingRight: 6,
  },
  totalToPayValue: { color: STONE_900, fontFamily: "Helvetica-Bold", fontSize: 11.5 },
  totalPaymentBlock: { width: "100%", marginTop: 2, alignItems: "flex-end" },
  grandBlock: { marginTop: 4, width: "100%" },
  footer: {
    marginTop: 10,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: STONE_200,
  },
  footerText: {
    fontSize: 6.5,
    color: STONE_500,
    textAlign: "center",
    lineHeight: 1.25,
  },
});

export type ReceiptPdfStyleSheet =
  | typeof receiptPdfStylesDark
  | typeof receiptPdfStylesLight;

export function getReceiptPdfStyles(theme: ReceiptPdfTheme): ReceiptPdfStyleSheet {
  return theme === "LIGHT" ? receiptPdfStylesLight : receiptPdfStylesDark;
}
